#ifndef CONFIG_H
#define CONFIG_H

/*INTERFACE CONFIGS*/
#define SHOW_LOGS 1

/*FRAME CONFIGS*/
#define WINDOW_SIZE 5
#define FRAME_DATA_SIZE 63
#define MAX_SEQ 32

/*ERRORS CONFIGS*/
#define TEST_ERRORS 0
#define ERRORS_FREQ_DOWNLOAD 10000
#define ERRORS_FREQ_LIST 2
#define FIX_BUGGED_WINDOWS 1

/*SOCKET CONFIGS*/
#define INTERFACE_NAME "enp1s0"
#define TIMEOUT_SECONDS 15
#define MAX_RETIES 5

#endif